#!/bin/bash

#location of HPL 
#HPL_DIR=/home/cluster/benchmark/hpl-2.0_FERMI_v15

# Number of CPU cores ( per GPU used = per MPI process )
CPU_CORES_PER_GPU=14

# FOR MKL
export MKL_NUM_THREADS=$CPU_CORES_PER_GPU
# FOR GOTO
export GOTO_NUM_THREADS=$CPU_CORES_PER_GPU
# FOR OMP
export OMP_NUM_THREADS=$CPU_CORES_PER_GPU

export MKL_DYNAMIC=FALSE

# hint: for 2050 or 2070 card
#       try 350/(350 + MKL_NUM_THREADS*4*cpu frequency in GHz) 
export CUDA_DGEMM_SPLIT=1.00

# hint: try CUDA_DGEMM_SPLIT - 0.10
export CUDA_DTRSM_SPLIT=0.90

export LD_LIBRARY_PATH=hpl/src/cuda:$LD_LIBRARY_PATH

source /opt/intel/bin/compilervars.sh intel64
./hpcc
#mpirun -n 2 ./hpcc 
#mpirun -f host_4node -n 8 -ppn 2 $HPL_DIR/bin/CUDA/xhpl
